[jsx]
jsx = "react"
jsxFactory = "v"
jsxFragment = "v.fragment"

[test]
timeout = 10000
coverage = true
coverageDir = "./coverage"
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coverageThreshold = { lines = 0.85, functions = 0.0, statements = 0.85 }
coveragePathIgnorePatterns = [
  "tests/**",
  "scripts/**"
]